# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos1706_v3"
  config.ssh.insert_key = false
  config.vm.define :centos_node3 do |node3|
    node3.vm.box = "centos1706_v3"
    node3.vm.network "public_network", bridge: "eno1", ip:"192.168.131.105", netmask: "255.255.255.0"
    node3.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "1024","--cpus", "1", "--name", "centos_node3" ]
    end
  config.vm.provision "shell", path: "install.sh"
  end

end
